<?php
session_start();
require_once('connectvars.php');
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The Writers Among Us - Home</title>
     <link rel="stylesheet" type="text/css" href="style.css" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<img src="images/homepageImage.png" style="width:80%; margin-left:10%; margin-right:10%; margin-top: 2em; height=auto;" alt="Image of spiral bound notebooks and a cup of coffee with a spoon. The text 'The Writers Among Us' is overlayed on the right side of the image in white." />

<!-- <script>

var myVar = setInterval(myTimer, 1000);

function myTimer() {
  alert("test");
}
</script> -->

<?php
require_once('navbar.php');
 ?>

<br />
<section style="width: 35%; margin-left: 12%; float: left;">
<article style="width: 100%; border: 10px solid #907558; padding-right: 3em; padding-left: 3em; padding-top: 1em; padding-bottom: 1em; overflow: auto; height: 15em;">

<?php
$dbc = mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
$sql = "SELECT event_id, event_type, event_amount FROM EVENT_DATA WHERE event_status = 'N' AND public = 2 ORDER BY creation_date";
$result = mysqli_query($dbc, $sql);
while ($row = mysqli_fetch_array($result)) {
  $currentEvent = null;
  if ($row['event_type'] == 'S') {
    $currentEvent = "word Sprint";
  } else if ($row['event_type'] == 'W') {
    $currentEvent = "minute War";
  } else if ($row['event_type'] == 'C') {
    $currentEvent = "Crawl";
  }
  echo '<p style="color: #907558"><a href="sprints.php?id=' . $row['event_id'] . '"><img src="images/goButton.png" style="height: 30px; width: auto; padding-right: 1em;" alt="Brown button with the word \'Go\' in white" /></a>' . $row['event_amount'] . ' ' . $currentEvent . '</p>';
}
 ?>

  <!-- Links generated by what's available -->
</article>
  <h3 style="text-align: center;">New</h3>
</section>

<section style="width: 35%; margin-left: 6%; float: left;">
<article style="width: 100%; border: 10px solid #907558; padding-right: 3em; padding-left: 3em; padding-top: 1em; padding-bottom: 1em; overflow: auto; height: 15em;">

<?php
  $dbc = mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
  $sql = "SELECT event_id, event_type, event_amount FROM EVENT_DATA WHERE event_status = 'P' AND public = 2 ORDER BY creation_date";
  $result = mysqli_query($dbc, $sql);
  while ($row = mysqli_fetch_array($result)) {
    $currentEvent = null;
    if ($row['event_type'] == 'S') {
      $currentEvent = "word Sprint";
    } else if ($row['event_type'] == 'W') {
      $currentEvent = "minute War";
    } else if ($row['event_type'] == 'C') {
      $currentEvent = "Crawl";
    }
    echo '<p style="color: #907558"><a href="sprint.php?id=' . $row['event_id'] . '"><img src="images/goButton.png" style="height: 30px; width: auto; padding-right: 1em;" alt="Brown button with the word \'Go\' in white" /></a>' . $row['event_amount'] . ' ' . $currentEvent . '</p>';
  }
  ?>

  <!-- Links generated by what's available -->
</article>
  <h3 style="text-align: center;">In Progress</h3>
</section>

<br /><br /><br /><br />

<section style="clear: both; width: 60%; margin-right: auto; margin-left: auto;">
  <h3 style="text-align: center;">Welcome!</h3>
  <p "text-align: center;">Welcome to the Writers Among Us. This is a site meant to help writers get words down for their stories. Sometimes you need a bit of competition or motivation from your friends to get all the words on the page and thats exactly what this is meant for.</p>
  <!-- Help Button -->
</section>

<?php
mysqli_close($dbc);
 ?>
</body>
</html>
