<?php
session_start();

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>The Writers Among Us - Sprints</title>
     <link rel="stylesheet" type="text/css" href="style.css" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<?php
if (!isset($_SESSION['user_id'])) {
  // Redirect to My Account page
  $home_url = 'http://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']) . '/login.php';
  header('Location: ' . $home_url);
}

require_once('navbar.php');

  ?>

  <h1 style="text-align: center; color: #907558;">Word Sprints Home</h1>
  <p style="text-align: center; color: #907558; width: 60%; margin-left: auto; margin-right: auto;">Welcome to the home for word sprints. What is a word sprint? Its when a group of people get together to try and reach a specific word goal first. It can be a competition to be the first to finish or just encourage you as your friends make the goal with you.</p>

  <br />
  <section style="width: 35%; margin-left: 12%; float: left;">
  <article style="width: 100%; border: 10px solid #907558; padding-right: 3em; padding-left: 3em; padding-top: 1em; padding-bottom: 1em; overflow: auto; height: 15em;">

  <?php
  $dbc = mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
  $sql = "SELECT sprint_id, goal  FROM SPRINT_DATA WHERE status = 'N' ORDER BY creation_date";
  $result = mysqli_query($dbc, $sql);
  while ($row = mysqli_fetch_array($result)) {
    echo '<p style="color: #907558"><a href="sprints.php?id=' . $row['sprint_id'] . '"><img src="images/goButton.png" style="height: 30px; width: auto; padding-right: 1em;" alt="Brown button with the word \'Go\' in white" /></a>' . $row['goal'] . ' word Sprint</p>';
  }
   ?>

    <!-- Links generated by what's available -->
  </article>
    <h3 style="text-align: center;">New</h3>
  </section>

  <section style="width: 35%; margin-left: 6%; float: left;">
  <article style="width: 100%; border: 10px solid #907558; padding-right: 3em; padding-left: 3em; padding-top: 1em; padding-bottom: 1em; overflow: auto; height: 15em;">

  <?php
    $dbc = mysqli_connect(DB_HOST, DB_USER, DB_PASSWORD, DB_NAME);
    $sql = "SELECT sprint_id, goal  FROM SPRINT_DATA WHERE status = 'P' ORDER BY creation_date";
    $result = mysqli_query($dbc, $sql);
    while ($row = mysqli_fetch_array($result)) {

      echo '<p style="color: #907558"><a href="sprints.php?id=' . $row['sprint_id'] . '"><img src="images/goButton.png" style="height: 30px; width: auto; padding-right: 1em;" alt="Brown button with the word \'Go\' in white" /></a>' . $row['goal'] . ' word Sprints</p>';
    }
    ?>

    <!-- Links generated by what's available -->
  </article>
    <h3 style="text-align: center;">In Progress</h3>
  </section>

  <section style="width: 14%; height: auto; margin-left: auto; margin-right: auto;"><a href="newSprint.php"><img src="images/createNewButton.png" alt="Create New Sprint" style="width: 100%;" /></a></section>

 </body>
 </html>
